### ISSUE TITLE
RestAssured Filter not works

### ISSUE THREAD

**Issue by alterhu2020** [dzieciou/curl-logger#151] opened 2023-10-10 14:48 UTC
# Configuration

1. Platform: MacOS Pro
2. curl-logger: 3.0.0

# Problem

1. Create a RestAssured Filter and then in the filter to add curl-logger config change, but it not works:
```
import com.github.dzieciou.testing.curl.CurlCommand;
import com.github.dzieciou.testing.curl.CurlRestAssuredConfigFactory;
import com.github.dzieciou.testing.curl.Options;
import com.github.dzieciou.testing.curl.Platform;
import io.restassured.RestAssured;
import io.restassured.config.HttpClientConfig;
import io.restassured.config.RestAssuredConfig;
import io.restassured.filter.FilterContext;
import io.restassured.filter.OrderedFilter;
import io.restassured.response.Response;
import io.restassured.specification.FilterableRequestSpecification;
import io.restassured.specification.FilterableResponseSpecification;
import org.slf4j.event.Level;

public class CommandFilter implements OrderedFilter {


    @Override
    public Response filter(FilterableRequestSpecification requestSpec, FilterableResponseSpecification responseSpec, FilterContext ctx) {
         Options options = Options.builder()
                .dontLogStacktrace()
                .printMultiliner()
                .useLogLevel(Level.INFO)
                .targetPlatform(Platform.UNIX).build();
        RestAssured.config = CurlRestAssuredConfigFactory.updateConfig(RestAssured.config, options);
        return ctx.next(requestSpec, responseSpec);
    }

    @Override
    public int getOrder() {
        return LOWEST_PRECEDENCE;
    }
}
```
and test code as following:

```
 RestAssured.given().baseUri("https://google.com").config(RestAssured.config).filters(new CommandFilter()).get("/");
```

3. Actual result:  the CurlGeneratingInterceptor never been executed, so curl not been printed
5. Expected result: can change the RestAssuredConfig and print the curl command

**Comment by francislainy** [comment] 2023-10-10 15:49
Hi, do you have a logback.xml file configured? I believe this is needed for the logs to work as described in the readme section here: https://github.com/dzieciou/curl-logger#configuring-logger

This is the logging config for my project:
https://github.com/francislainy/HelloTalk/blob/master/src/test/resources/logback-test.xml

**Comment by alterhu2020** [comment] 2023-10-11 03:14
> Hi, do you have a logback.xml file configured? I believe this is needed for the logs to work as described in the readme section here: https://github.com/dzieciou/curl-logger#configuring-logger
> 
> This is the logging config for my project: https://github.com/francislainy/HelloTalk/blob/master/src/test/resources/logback-test.xml

yes, add the logback config file here, but still not works:

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>

    <appender class="ch.qos.logback.core.ConsoleAppender" name="STDOUT">
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>


    <root level="INFO">
        <appender-ref ref="STDOUT"/>
    </root>

</configuration>
```

**Comment by francislainy** [comment] 2023-10-11 03:49
Have you made sure your application is supporting logback by adding the necessary dependencies for it?

**Comment by alterhu2020** [comment] 2023-10-11 06:58
> Have you made sure your application is supporting logback by adding the necessary dependencies for it?

yes, add the loback deps as following:
```
 <dependencies>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
            <version>1.3.5</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>2.0.7</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.3.5</version>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <version>5.3.2</version>
            <exclusions>
                <exclusion>
                    <groupId>org.hamcrest</groupId>
                    <artifactId>hamcrest-library</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.hamcrest</groupId>
                    <artifactId>hamcrest-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.github.dzieciou.testing</groupId>
            <artifactId>curl-logger</artifactId>
            <version>3.0.0</version>
        </dependency>
    </dependencies>
```
the problem here is when I use the RestAssured Filter it doesn't work, but if i change to use the followning code, it works:
```
RestAssuredConfig restAssuredConfig = CurlRestAssuredConfigFactory.updateConfig(RestAssured.config(), options);
       RestAssured.config.httpClient(new HttpClientConfig().dontReuseHttpClientInstance());
        RestAssured.given().baseUri("https://google.com").config(RestAssured.config).filters(new CURLStorage()).get("/");
```

**Comment by dzieciou** [comment] 2023-11-10 08:06
I rarely look at this library nowadays. I will try to dig into that this weekend.

**Comment by dzieciou** [comment] 2023-11-11 14:52
@alterhu2020 

The reason you're not getting curl commands logged is that `RequestSpecificationImpl` uses `RestAssuredConfig` instance before it gets updated by your filter:

https://github.com/rest-assured/rest-assured/blob/master/reRequestSpecificationImplst-assured/src/main/groovy/io/restassured/internal/RequestSpecificationImpl.groovy#L1686

This is by design and if you want that to be changed you should contact the authors of REST-assured.

Is there any specific reason you're trying to update `RestAssured.config` inside of a filter?

**Comment by dzieciou** [comment] 2023-11-18 13:23
Closing as this is not a bug.

**Closed by dzieciou** 2023-11-18 13:23 UTC
Labels: bug
